---
name: Alejandro
surname: Sánchez Peralta
position: "Head of Department"
address: "National Institute of Statistics and Geography"
phone: +52 55 2758 0678
profilepic: alex_2.png

email: "sanchez.alexito@gmail.com"
twitter: san_alehandro  
linkedin: sanchez-peralta-alejandro
github: sanalexito
date: "`r format(Sys.Date(), '%B %Y')`"
aboutme: "Data scientist with experience of more than five years in the information procesing and survey analisys for the INEGI. Among other functions, I am in charge of generating the official information at the country level of the ENVE, the ENCRIGE and the ENCIG. I have knowledge in statistics and fluency in managing, cleaning, analyzing and visualizing data using R, Python and Power BI tools. I like to address the generation of value from raw data."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# WORK EXPERIENCE

## INEGI    

## Head of Department, 2016 - To date.

* Data cleaning, preparation and validation for the correct generation of survey KPIs (ENVE, ENCRIGE and ENCIG) using data wrangling libraries such as Tidyverse, Dplyr, Stringr in R; or Pandas when the use of Python is required.

* Collaboration with data engineers and other data scientists for the implementation of models that support decision-making based on quantitative evidence. This includes the design of dashboards with Shyni or Power BI and the generation of tabulations in Excel. 
 
* Integration of the documentation of the validation process of the information streams of different surveys, as well as the generation of technical reports through Markdown and Google Colaboratory.

* Key achievements in my actual role include redesigning computational processes department-wide to improve efficiency in 30%. I also been able to improve production quality, through implementation of text analysis, which reduced delivery times by 25%.
 
  
## INEGI

## Jr Data Analyst, 2015 - 2016.

* Review and data contrast in executive presentations on issues of public safety, victimization and law enforcement.

* Elaboration of forecasts for different public security indicators such as total crimes or the "dark number of crimes" using the Forecast library.

* Calculation of different indicators for the National Government Surveys using the Survey library of R.

## UAM-I

## Associate Professor, 2010 - 2015.

* Quarterly class planning. Organization of workshops and consultancies to complement the academic training of students. In this position, in addition to teaching, I have been part of the organizing committee of the XXI and XXII Week of Mathematics, which takes place annually in the Mathematics Department of UAM-Iztapalapa. 

# Education
 * [\color{mainblue}{Power BI - Data Analysis and Business Intelligence, 2022, Ûdemy (21 hours.}](https://udemy-certificate.s3.amazonaws.com/pdf/UC-024bbc1d-e043-4c42-81af-d38911aef436.pdf)
 * [\color{mainblue}{Results Based Budgeting Diplomate, 2022. SHCP (120 hours)}](https://drive.google.com/file/d/1C7xov9FNW8QIL6GXNMRNRVJNBmozsHCz/view?usp=sharing)
 * Master of Mathematics, 2010, Universidad Autónoma Metropolitana-Iztapalapa.
 * Bachelor of Mathematics, 2007, Universidad Autónoma Metropolitana-Iztapalapa.


# Publications

* [\color{mainblue}{mainblue}{Final Offer Arbitration.}](https://rde.inegi.org.mx/index.php/2017/12/18/arbitraje-oferta-final-determinacion-del-pago-optimo-en-conflicto-ambiental/) Determination of the optimal payment in an environmental dispute, Reality, Data and Space. International Journal of Statistics and Geography, Vol.8, No.3, pp.15-29, 2017.,
  

# Extracurricular activities {data-icon=images}

 * [\color{mainblue}{Transparency Innovation Contest 2021.}](https://aplicacionasp.shinyapps.io/datatonicos_app/?_ga=2.114794881.748076323.1652235506-1286185329.1634413335) <p>
Participation in the "First Dataton on the Platform Your City, Your Money" organized by the Digital Agency for Public Innovation<br /> ([ADIP](https://dataton2021.tudinero.cdmx.gob.mx/)
) with the Income Analysis Project of the Mexico City Metro.

\newpage

<b>

<b>

</br>

* [\color{mainblue}{Insecurity Perception Platform.}](https://aplicacionasp.shinyapps.io/plapim_app/?_ga=2.9462451.748076323.1652235506-1286185329.1634413335#section-inicio)
<p>Development of the platform with National Survey on Victimization and Perception on Public Safety (ENVIPE) data, 05-2020.


